### ISSUE TITLE
How to get starting tree for snaq!() use SNPs?

### ISSUE THREAD

**Issue by xiekunwhy** [melisaolave/SNPs2CF#2]
Hi,

How to get starting tree for snaq!() use SNPs only ?

Best wishes,
Kun

**Comment by melisaolave** [comment]
Hi Kun,

you need to estimate a tree with your SNP dataset. You could use many different programs, but I would recommend you to go with a coalescent species tree method that takes SNPs, like SVDquartets in PAUP*: http://www.phylosolutions.com/tutorials/ssb2018/svdquartets-tutorial.html

Melisa
