### ISSUE TITLE
Very low number of genes/SNPs ("ngenes") in csv table (RADseq)

### ISSUE THREAD

**Issue by kevinkarbstein** [melisaolave/SNPs2CF#3]
Dear Melisa,

I was successful in implementing your SNPs to CF R analysis (v. 1.4). I use a RADseq alignment (ca. 30,000 loci; 400,000 SNPs; 50% missing data) as input alignment. 
However, the final number of "ngenes" per quartet, i.e., the proportion of SNPs (orgenes for gene-based analyses) whose true tree supports that particular quartet (Olave & Meyer 2020), is very low in my analyses. I was wondering because I only received 7-20 ngenes per quartet but I have more than 30,000 SNPs (unlinked alignment, 1 SNP/locus and 30,000 loci) within the analysis. 
My questions: Do only a few SNPs support the specific quartet or is there a general methodological issue with gappy RADseq alignments?

I attached an exemplary file.

[quartet_1.xlsx](https://github.com/melisaolave/SNPs2CF/files/5554358/quartet_1.xlsx)

Best regards,

Kevin

**Comment by melisaolave** [comment]
Hi Kevin,

this means that you only have 7-20 SNPs that are informative for the CF calculations among species quartets. This is not an issue of the R function, but a limitation of your dataset. For example, if you have lots of singletons, they are not informative. Also, remember that ambiguities, indels and missing data are ignored. Make sure of separating phases, so ambiguity information is not lost.

If you are subsampling individuals/species from the original phylip matrix with 30K SNPs (either using nquartets, or excluding individuals/species from the Imap), then it is likely that you actually have many fewer SNPs for your sampled individuals than 30K. If this is the case, something you could do is to get a phylip matrix with already filtered individuals/species. That might help increasing the number of informative SNPs for your target group.

Melisa
