### ISSUE TITLE
specified 100 bootstraps only 10 replicates were run in phylonetworks

### ISSUE THREAD

**Issue by smallfishcui** [melisaolave/SNPs2CF#4]
Hi,

I prepared the quartets for phylonetworkd using SNPs generated from RADseq dataset, using this command,
output <- SNPs2CF(seqMatrix="populations.phy", ImapName="Imap_finrad_noOGY48K12.txt", between.sp.only = TRUE, max.SNPs = 41295, bootstrap=TRUE,boots.rep=100, n.quartets = 500, outputName="SNPs2CF_7taxa-41K_500quar_finerad_boots.csv", save.progress=FALSE,cores = 10)
however after run the phylonetworks I only get 10 bootstrap. Do you know what could be the reason?

Thanks,
Cui

**Comment by melisaolave** [comment]
Hi Cui, 
this doesn't sound like a problem with SNPs2CF, but PhyloNetworks. Make sure of specifying the number of bootstrap replicates using nrep = 100 with bootsnaq in PhyloNetworks.

follow instructions here: http://crsl4.github.io/PhyloNetworks.jl/latest/man/bootstrap/

Melisa

**Comment by smallfishcui** [comment]
Okay thanks for pointing it out Melisa! I guess I have missed to put the right parameter in phylonetwork then.. I ll close this issue now.

Cui
