### ISSUE TITLE
Error - doubling sample names for haplotypes

### ISSUE THREAD

**Issue by ghost** [melisaolave/SNPs2CF#5]
Hello Melisa,

First of all, thank you for creating this super useful tool! 

After creating my .phy file using the **phased.vcf2phylip** function, when running the **SNPs2CF**, I get a warning that all the individual names in the matrix were not found in the Imap file; and then an error. After futher inspection I realized that the **phased.vcf2phylip** function places a **_0** and a **_1** after each name for the two haplotypes. 

Here is the error that I get:

`> aglais_CF <- SNPs2CF(seqMatrix="aglais_NO_50missing_unlinked_forCF.vcf.phy", max.SNPs = NULL, bootstrap=FALSE, outputName="aglais_CF.csv", save.progress=FALSE, between.sp.only = TRUE,ImapName = "pops.txt",cores = 5)

Read 147 items
Reading Imap file
Two columns are expected, first column are the individuals (or alleles) and second column are the species
WARNING: Some individual names in the SNP matrix were not found in Imap. Only those listed in the Imap file will be used for CF calculations. Individuals not found:
 Aurticae_RVcoll06A037_Granada_Spain_0   Aurticae_RVcoll06A037_Granada_Spain_1   Aurticae_RVcoll07F571_Nepal_0   Aurticae_RVcoll07F571_Nepal_1 (...)
5 species found in Imap: Eastern European Peloponnese Sicily/South_Italy Sierra_Nevada 
All possible species quartets for 5 species: 5 
n.quartets = all, thus CF will be calculated from all possible quartets
Getting CF calculations. There is not progress report when running in parallel. This could take several minutes/hours, please be pacient...
Error in { : task 1 failed - "subscript out of bounds"`

My question is, do I have to double the individual names and add the **_0/1** to the Imap file?

Thank you in advance for the help, sorry if this is very simple, I am a beginner in computational biology.

**Comment by melisaolave** [comment]
Hi Valeria,

yes, it looks like the problems comes from individuals ID incompatibilities between the phylip matrix and Imap. After using phased.vcf2phylip you get a matrix with two alleles per individual (assuming diploid individuals). So, yes, you need to modify your Imap to include both alleles, exactly as they are named in the phylip matrix (using _0 and _1).

let me know if you still get an error, and feel free to send the input files so I can take a look
all the best,

Melisa
