### ISSUE TITLE
Fails on last species quartet 

### ISSUE THREAD

**Issue by cmt2** [melisaolave/SNPs2CF#7]
Hello, 

I'm trying to run SNPs2CF on a file of 24 taxa, ~4000 SNPs. When I run on that dataset, I get an error when calculating the final species quartet:

`Error in { : task 18 failed - "subscript out of bounds"
`
I'm able to run the analysis on a much reduced dataset of 5 taxa (same SNPs). I'm having a hard time tracking down this error message, any tips would be much appreciated!

**Comment by melisaolave** [comment]
Hi Carrie,
it looks like a formatting issue. Could you send me your phylip matrix and Imap? 
Melisa

**Comment by cmt2** [comment]
Hi Melisa,

Sure! Thanks. Here are the files. Just for the upload, I changed the phylip matrix file to a .txt as .phy isn't supported on GitHub. 

[dory_HI_imap.txt](https://github.com/melisaolave/SNPs2CF/files/12113460/dory_HI_imap.txt)
[Dory_LD_pruned_SNPs_variant.recode.names_fixed.vcf.hawaii.txt](https://github.com/melisaolave/SNPs2CF/files/12113465/Dory_LD_pruned_SNPs_variant.recode.names_fixed.vcf.hawaii.txt)

**Comment by melisaolave** [comment]
Hi Carrie, 
there are " | " and " / " in the matrix. Did you use vcf2phylip function to convert vcf into phylip? there might be a problem with this function compatibilities with your vcf. 
So far, vcf2phylip works well with dDocent and Stacks outputs, as well as beagle and SHAPEIT outputs after phasing. What program did you use to process your vcf?

Melisa

**Comment by melisaolave** [comment]
Ah, I remember seeing something like this before, in cases where there are complex variants in the vcf. For example, dDocent doesn't process complex variants, you have to do afterwards. Please check if that is the case.
It is also good to remove indels.

**Comment by cmt2** [comment]
Hi Melisa,

Thanks! The data are from target capture, but my collaborator used a custom
pipeline to call SNPs. I'll have to check with him about the "/" and "|".
I'll look into this more and check back with you if I have any questions.
Thanks for your quick and helpful response! I'll close the issue now.

cheers,
Carrie
