### ISSUE TITLE
Matrix too large ?

### ISSUE THREAD

**Issue by pittt10** [melisaolave/SNPs2CF#8]
Hello,
I am running SNP2CF for a large dataset (312 individuals, more than 200 species)

`source("SNPs2CF-master/functions_v1.6.R")
library(foreach)
library(doMC)
library(pegas)
output <- SNPs2CF(seqMatrix="KEARAD1.phylip", ImapName="ImapKEAfull.txt", between.sp.only = FALSE, bootstrap=TRUE,
                  outputName="SNPs2CFKearad.csv", save.progress=TRUE, cores = 36)` 

and I am getting back this error

Loading required package: iterators
Loading required package: parallel
Loading required package: ape

Attaching package: ‘pegas’

The following object is masked from ‘package:ape’:

    mst

Read 613 items
Reading Imap file
Two columns are expected, first column are the individuals (or alleles) and second column are the species
306 species found in Imap: 115A15 116A16 168168 169169 170170 171171 172172 340X40 341X41 342X42 343X43 344X44 345X45 346X46 348X48 349X49 350X50 351X51 352X52 353X53 359X59 360X60 361X61 363X63 366X66 368X68 369X69 370X70 371X71 372X72 374X74 375X75 376X76 377X77 378X78 379X79 380X80 381X81 383X83 384X84 386X86 387X87 389X89 391X91 ancestral DRR057302 DRR057303 DRR057304 DRR057305 EDSW200005870-1a EDSW200005871-1a EDSW200005872-1a EDSW200005873-1a EDSW200005874-1a EDSW200005875-1a EDSW200005876-1a EDSW200005877-1a EDSW200005878-1a EDSW200005879-1a EDSW200005880-1a EDSW200005881-1a EDSW200005882-1a EDSW200005883-1a EDSW200005884-1a EDSW200005885-1a EDSW200005886-1a EDSW200005887-1a EDSW200005888-1a EDSW200005889-1a EDSW200005890-1a EDSW200005891-1a EDSW200005892-1a EDSW200005893-1a EDSW200005895-1a EDSW200005896-1a EDSW200005897-1a EDSW200005898-1a EDSW200005899-1a EDSW200005900-1a EDSW200005901-1a EDSW200005902-1a EDSW200005904-1a EDSW200005905-1a EDSW200005906-1a EDSW200005907-1a EDSW200005908-1a EDSW200005909-1a EDSW200005910-1a EDSW200005911-1a EDSW200005912-1a EDSW200005913-1a EDSW200005914-1a EDSW200005915-1a EDSW200005916-1a EDSW200005917-1a EDSW200005918-1a EDSW200005919-1a EDSW200005920-1a EDSW200005921-1a EDSW200005922-1a EDSW200005923-1a EDSW200005924-1a EDSW200005925-1a EDSW200005926-1a EDSW200005927-1a EDSW200005928-1a EDSW200005929-1a EDSW200005930-1a EDSW200005931-1a EDSW200005932-1a EDSW200005933-1a EDSW200005934-1a EDSW200005935-1a EDSW200005936-1a EDSW200005937-1a EDSW200005938-1a EDSW200005939-1a EDSW200005940-1a EDSW200005941-1a EDSW200005943-1a EDSW200005944-1a EDSW200005945-1a EDSW200005946-1a EDSW200005947-1a EDSW200005948-1a EDSW200005949-1a EDSW200005950-1a EDSW200005951-1a EDSW200005952-1a EDSW200005953-1a EDSW200005954-1a EDSW200005955-1a EDSW200005956-1a EDSW200005958-1a EDSW200005959-1a EDSW200005960-1a EDSW200005961-1a EDSW200005962-1a EDSW200005964-1a EDSW200005966-1a EDSW200005967-1a EDSW200005968-1a EDSW200005969-1a EDSW200005970-1a EDSW200005972-1a EDSW200005973-1a EDSW200005975-1a EDSW200005976-1a EDSW200005977-1a EDSW200005978-1a EDSW200005980-1a EDSW200005981-1a ERR1081378 ERR1743779 ERR1743780 ERR1743781 ERR1805665 ERR1805666 ERR1822250 ERR1822251 ERR3634107 ERR3634108 ERR3634109 ERR3634110 ERR3634112 ERR3634113 ERR3634114 ERR3634115 SRR12394583 SRR12394594 SRR12394622 SRR12394623 SRR12394627 SRR12700808 SRR12700809 SRR12700810 SRR12700811 SRR12700812 SRR12700813 SRR12700814 SRR12700815 SRR12700816 SRR12700817 SRR12700818 SRR12700819 SRR12700820 SRR12700821 SRR12700822 SRR12700823 SRR12700824 SRR12700825 SRR12700826 SRR12700827 SRR12700828 SRR12700829 SRR12700830 SRR12700832 SRR12700833 SRR12700834 SRR12700835 SRR12700836 SRR12700837 SRR12700838 SRR12700839 SRR12700840 SRR12700841 SRR12700842 SRR12700843 SRR12700844 SRR12700845 SRR12700846 SRR12700847 SRR12700848 SRR12700849 SRR12700850 SRR12700851 SRR12700852 SRR12700853 SRR12700854 SRR12700855 SRR12700856 SRR12700857 SRR12700858 SRR12700859 SRR12700860 SRR12700861 SRR12700862 SRR12700863 SRR12700864 SRR12700865 SRR12700866 SRR12700867 SRR12700868 SRR12700869 SRR12700870 SRR12700871 SRR12700872 SRR12700873 SRR12700874 SRR12700875 SRR12700876 SRR12700877 SRR12700878 SRR12700879 SRR12700880 SRR12700881 SRR12700882 SRR12700883 SRR12700884 SRR12700885 SRR12700886 SRR12700887 SRR12700888 SRR12700889 SRR12700890 SRR12700891 SRR12700892 SRR12700893 SRR12700894 SRR12700895 SRR12700896 SRR12700897 SRR12700898 SRR12700899 SRR12700900 SRR12700901 SRR12700902 SRR12700903 SRR12700904 SRR12700909 SRR12700910 SRR12700911 SRR2886825 SRR2886826 SRR2886827 SRR2886828 SRR4169629 SRR5099812 SRR5099819 SRR5099858 SRR5221055 SRR5221056 SRR7662358 SRR7662363 SRR7662383 SRR7662384 SRR7662386 SRR7662390 SRR7662398 SRR7662401 SRR7662402 SRR7662405 SRR7662410 SRR7662423 SRR7662424 SRR7662436 SRR7662443 SRR7662449 SRR7662461 SRR7662473 SRR9657520 SRR9657521 SRR9673865 SRR9673933 SRR9673939 SRR9675392
Error in matrix(r, nrow = len.r, ncol = count) :
  invalid 'ncol' value (too large or NA)
Calls: SNPs2CF -> combn -> matrix
In addition: Warning message:
In combn(x = 1:n.sp, m = 4) : NAs introduced by coercion to integer range
Execution halted

The function works perfectly with a smaller database but it fails with the full one. I am running it on the cluster so it should not be a memory issue, do you have any idea where the problem could be ?
Thanks in advance,

Pietro

**Comment by melisaolave** [comment]
Hi Pietro,

I’m not 100% sure if this specific error is due to the matrix being too large (my impression is that it might be a format error in the matrix), but yes, your matrix is way too large. With 200 species, you would have about 65 million species quartets, multiplied by the combinations added by the individual quartets. Even if you get SNPs2CF to produce the CF calculations, it will be computationally impossible for PhyloNetworks to infer a network with 200 species.In my experience so far, PhyloNetworks has been able to work on up to 20 species (it takes a few weeks). Higher numbers are too time-consuming.

My recommendation is to consider partitioning your matrix into different subclades and running separate networks for groups of up to 20 species each. If you still get the same error with some of these matrices, please write again. It would be useful if you could share the matrix used as input that led to the error.

Good luck,

Melisa
